logging:
  level:
    org.thymeleaf: DEBUG

spring:
  application:
    name: Jpa Final Project Alex Bard

  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/finalproject?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      max-active: 5
      max-idle: 3
      max-wait: 8000

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    schemas: finalproject
